import type { ObservatoryState } from "./types";

export const defaultState: ObservatoryState = {
  concreteHeight: 0.85,
  pierDiameter: 0.3,
  extensionHeight: 0.12,
  pivotOffset: -0.05,
  mountHeight: 0.12,
  latitude: -23.7,
  baseOffset: 0.095,
  rightAscensionOffset: 0.22,
  declinationOffset: 0.35,
  counterweightOffset: 0.48,
  tubeLength: 0.559,
  tubeOffset: 0.05,
  eyepieceLength: 0.04,
  tubeDiameter: 0.272,
  roomWidth: 3.65,
  roomDepth: 2.8,
  roomHeight: 2.2,
  roofOpen: 0,
  roofPitch: 15,
  roofDirection: "N",
  rightAscension: 0,
  declination: -90,
  showFurniture: true,
  sofaBedOpen: false,
  showVolume: true,
  showObserver: true,
  observerPosture: "sitting",
  observerX: 1,
  observerZ: 0,
  skyHour: -1,
  skyDay: -1,
  panoramaRotation: 0,
  showGemOverlay: true,
  showBlockOverlay: true,
  showMeridianOverlay: true,
};
