import type { BrightStar } from "./types";

export const BRIGHT_STARS: readonly BrightStar[] = [
  { name: "Sirius", rightAscension: 101.3, declination: -16.7, magnitude: -1.5 },
  { name: "Canopus", rightAscension: 96, declination: -52.7, magnitude: -0.7 },
  { name: "α Centauri", rightAscension: 219.9, declination: -60.8, magnitude: -0.3 },
  { name: "Arcturus", rightAscension: 213.9, declination: 19.2, magnitude: -0.1 },
  { name: "Vega", rightAscension: 279.2, declination: 38.8, magnitude: 0 },
  { name: "Capella", rightAscension: 79.2, declination: 46, magnitude: 0.1 },
  { name: "Rigel", rightAscension: 78.6, declination: -8.2, magnitude: 0.1 },
  { name: "Procyon", rightAscension: 114.8, declination: 5.2, magnitude: 0.3 },
  { name: "Achernar", rightAscension: 24.4, declination: -57.2, magnitude: 0.5 },
  { name: "Betelgeuse", rightAscension: 88.8, declination: 7.4, magnitude: 0.5 },
  { name: "Altair", rightAscension: 297.7, declination: 8.9, magnitude: 0.8 },
  { name: "Aldebaran", rightAscension: 69, declination: 16.5, magnitude: 0.9 },
  { name: "Antares", rightAscension: 247.4, declination: -26.4, magnitude: 1 },
  { name: "Spica", rightAscension: 201.3, declination: -11.2, magnitude: 1 },
  { name: "Pollux", rightAscension: 116.3, declination: 28, magnitude: 1.1 },
  { name: "Fomalhaut", rightAscension: 344.4, declination: -29.6, magnitude: 1.2 },
  { name: "Deneb", rightAscension: 310.4, declination: 45.3, magnitude: 1.3 },
  { name: "Mimosa", rightAscension: 191.9, declination: -59.7, magnitude: 1.3 },
  { name: "Acrux", rightAscension: 186.6, declination: -63.1, magnitude: 1.3 },
  { name: "Regulus", rightAscension: 152.1, declination: 12, magnitude: 1.4 },
  { name: "Gacrux", rightAscension: 187.8, declination: -57.1, magnitude: 1.6 },
  { name: "Shaula", rightAscension: 263.4, declination: -37.1, magnitude: 1.6 },
  { name: "Castor", rightAscension: 113.6, declination: 31.9, magnitude: 1.6 },
  { name: "Bellatrix", rightAscension: 81.3, declination: 6.3, magnitude: 1.6 },
  { name: "Alnilam", rightAscension: 84.1, declination: -1.2, magnitude: 1.7 },
  { name: "Alnitak", rightAscension: 85.2, declination: -1.9, magnitude: 1.7 },
  { name: "Mintaka", rightAscension: 83, declination: -0.3, magnitude: 2.2 },
];
